apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: alpine
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: techtrends
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: alpine
    spec:
      containers:
      - image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        name: techtrends
      # Expose the port the container is listening on.
        ## For example, exposing the application port 6112 via TCP.
        ports:
        - containerPort: 3111
          protocol: TCP
        livenessProbe:
           httpGet:
             path: /healthz
             port: 3111
        readinessProbe:
           httpGet:
             path: /healthz
             port: 3111
        resources:
 {{ toYaml .Values.resources | indent 12 }}
