apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
    tag: tech-trends-project
  name: ubtech-trends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  type: ClusterIP
